security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Ilc\Bundle\ShopBundle\Entity\Client:
            algorithm: md5
            iterations: 1
            encode_as_base64: false
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODO]
        ROLE_MODO:        ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
