security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Ilc\Bundle\ShopBundle\Entity\Client:
            algorithm: md5
            iterations: 1
            encode_as_base64: false
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODO]
        ROLE_MODO:        ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: IlcShopBundle:Client }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: ~
            provider:  main
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 jours en secondes
                path:     /
                domain:   ~ 
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /

        default:
            anonymous: ~
